name: android audio build

on:
  workflow_dispatch:
jobs:
  build-android-main-on-linux:
    name: android main on linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: set up adopt jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: prerequisites
        run: sudo apt-get install autoconf automake libtool pkg-config curl git doxygen nasm cmake gcc gperf texinfo yasm bison autogen wget autopoint meson ninja-build ragel groff gtk-doc-tools libtasn1-bin

      - name: prerequisites 2
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"

      - name: upgrade meson
        run: pip install meson --upgrade

      - name: set up android ndk
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-r25b-linux.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV

      - name: run the build script
        run: ./android.sh -d --enable-android-media-codec --enable-android-zlib --enable-lame --enable-libilbc --enable-libvorbis --enable-opencore-amr --enable-opus --enable-shine --enable-soxr --enable-speex --enable-twolame --enable-vo-amrwbenc

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar